### ISSUE TITLE
Zoom on move with fingers/thumbs breaks scrolling on iOS

### ISSUE THREAD

**Issue by fire015** [willnguyen1312/zoom-image#317] opened 2024-09-02 11:43 UTC
### Describe the bug

Hey, great package! I just noticed on my own site (and I can confirm the same bug is on your demo page too) if you use 2 fingers/thumbs to zoom on move into the image (which is what I noticed my users naturally doing), the move zoom effect takes place correctly but once you have let go and its zoomed out again, you can no longer scroll up and down the page.

This is on my iPhone version 17.4.1 tested in Safari and Chrome.

Even with disabledContextMenu set to true it's the same issue. Hope you can help :)

### Reproduction

https://willnguyen1312.github.io/zoom-image/

### Used Package Manager

npm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/willnguyen1312/zoom-image/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is available

**Comment by willnguyen1312** [comment] 2024-09-04 16:46
Hi Jason, thanks for your feedback. I'm going to have a look later today after work. Thanks :)

**Comment by willnguyen1312** [comment] 2024-09-04 18:45
Hi @fire015. can you update the dependency to latest version and try again. Hope it helps. Thanks :)

**Comment by fire015** [comment] 2024-09-05 06:36
Working now thanks 🤙🏻

**Comment by fire015** [comment] 2024-09-05 09:08
Ok so on desktop this is now broken for me (I think my issue not yours) here is my code (using next & tailwind)...

```jsx
  useEffect(() => {
    if (imageMoveContainerRef.current && images[imageIndex]) {
      createZoomImage(imageMoveContainerRef.current, {
        zoomImageSource: images[imageIndex].src,
      });
    }
  }, [imageMoveContainerRef.current, imageIndex]);

  return (
    <form className="w-full">
      <div className="relative aspect-square h-full max-h-[550px] w-full overflow-hidden">
        {images[imageIndex] && (
          <div
            ref={imageMoveContainerRef}
            className="relative cursor-crosshair"
          >
            <NextImage
              className="h-full w-full object-contain"
              fill
              sizes="(min-width: 1024px) 66vw, 100vw"
              alt={images[imageIndex]?.altText as string}
              src={images[imageIndex]?.src as string}
              priority={true}
            />
          </div>
        )}
```

I noticed this happened in your previous update (0.4.20) so I reverted back to 0.4.19 but obviously would like this fix.

It's something to do with the relative class on imageMoveContainerRef, the image will not appear at all when the page loads. If I remove relative then the image appears but the zoom is stuck at the top of the image and doesn't follow the cursor around. Any suggestions?

**Comment by willnguyen1312** [comment] 2024-09-05 15:57
Hi Jason. I think it's another thing I need to look at later today 😃 

> after further debugging I can see the zoom image is no longer appended to the container

Sorry, I did it recently to solve one naughty bug in iOS [here](https://github.com/willnguyen1312/zoom-image/issues/314#issuecomment-2321776867). As I thought we don't need zoomed image sitting in the DOM unnecessary until it's needed.

Meanwhile, can you give me a reproduction repo of your issue. That will do a big push for my upcoming solution. Thanks :)

**Comment by willnguyen1312** [comment] 2024-09-05 17:06
I think I figured it out why. Injected zoom image needs to be aware of its wrapper's width and height to perform absolute positioning. Especially with Next's image, width and height are critical in their design to avoid layout shift because they can reserve the image's space while loading so there won't be any jumpy experience.

You can have a look at how I achieve it [here](https://github.com/willnguyen1312/next-zoom-image-library/blob/b5fac746236510e1779a3b9d0dd3c43dd3e1e201/app/page.tsx#L22-L37) using similar code as above by giving it some extra classes so wrapper element now has some specific dimensions inherited from its parent :)

**Comment by fire015** [comment] 2024-09-06 07:50
That fixed it, you are an absolute legend. Thanks!

**Comment by willnguyen1312** [comment] 2024-09-06 13:47
Awesome, I'm glad it helped. I'm going to close the issue. Thanks again for your feedback and please feel free to reach out if you need further support on the library's usage :)

**Closed by willnguyen1312** 2024-09-06 13:47 UTC
